networks:
  myapp:
    driver: bridge

services:
  php:
    image: php:8.3-apache
    container_name: myapp_php
    ports:
      - "8000:80"
    networks:
      - myapp
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    command: >
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql &&
               a2enmod rewrite &&
               sed -i 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf &&
               apache2-foreground"

  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:8.4
    container_name: myapp_mysql
    restart: unless-stopped
    networks:
      - myapp
    environment:
      MYSQL_ROOT_PASSWORD: "root@250270"
      MYSQL_USER: "presidente"
      MYSQL_DATABASE: "atacadao"
      MYSQL_PASSWORD: "inferno"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    networks:
      - myapp
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  mysql_data:
